#!/usr/bin/env node

import { createServer } from 'http'
import { execFile } from 'child_process'
import { writeFileSync, readFileSync, existsSync } from 'fs'
import { join } from 'path'
import { fileURLToPath } from 'url'

// SOLEDGIC_AUTH_URL overrides the website used for the browser auth flow during `init`.
// SOLEDGIC_BASE_URL is reserved for the API base URL used by doctor and the SDK at runtime —
// they intentionally point to different hosts (app vs api.) so they must be separate vars.
const AUTH_URL = process.env.SOLEDGIC_AUTH_URL ?? 'https://soledgic.com'
const TIMEOUT_MS = 300_000

function pickPort(): number {
  return Math.floor(Math.random() * 10_000) + 50_000
}

function openBrowser(url: string): void {
  if (process.platform === 'darwin') {
    execFile('open', [url], () => undefined)
  } else if (process.platform === 'win32') {
    execFile('cmd', ['/c', 'start', '', url], { windowsHide: true }, () => undefined)
  } else {
    execFile('xdg-open', [url], () => undefined)
  }
}

function writeEnv(key: string): void {
  const envPath = join(process.cwd(), '.env')
  const line = `SOLEDGIC_API_KEY=${key}`

  if (existsSync(envPath)) {
    const content = readFileSync(envPath, 'utf8')
    // Replace either the new (API_KEY) or legacy (SECRET_KEY) entry if present.
    if (/^SOLEDGIC_API_KEY=/m.test(content)) {
      writeFileSync(envPath, content.replace(/^SOLEDGIC_API_KEY=.*/m, line))
      return
    }
    if (/^SOLEDGIC_SECRET_KEY=/m.test(content)) {
      writeFileSync(envPath, content.replace(/^SOLEDGIC_SECRET_KEY=.*/m, line))
      return
    }
    writeFileSync(envPath, content.endsWith('\n') ? content + line + '\n' : content + '\n' + line + '\n')
  } else {
    writeFileSync(envPath, line + '\n')
  }
}

const TEST_FILE_NAME = 'soledgic-test-checkout.mjs'

const TEST_FILE_CONTENT = `// Generated by \`npx soledgic init\`. Safe to delete.
// Run once to verify your sandbox setup works end-to-end:
//   node ${'soledgic-test-checkout.mjs'}

import { readFileSync, existsSync } from 'fs'
import Soledgic from '@soledgic/sdk'

// Load .env manually so this file has zero extra dependencies.
if (existsSync('.env')) {
  for (const line of readFileSync('.env', 'utf8').split(/\\r?\\n/)) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq <= 0) continue
    const key = trimmed.slice(0, eq).trim()
    const value = trimmed.slice(eq + 1).trim().replace(/^["']|["']$/g, '')
    if (!process.env[key]) process.env[key] = value
  }
}

const apiKey = process.env.SOLEDGIC_API_KEY
if (!apiKey) {
  console.error('Missing SOLEDGIC_API_KEY. Run: npx soledgic init')
  process.exit(1)
}

const soledgic = new Soledgic({ apiKey })

async function main() {
  console.log('1/4  Upserting a test creator...')
  await soledgic.creators.upsert({
    externalCreatorId: 'test_creator_001',
    displayName: 'Test Creator',
    defaultSplitPercent: 80,
  })

  console.log('2/4  Creating a sandbox checkout...')
  const checkout = await soledgic.purchases.create({
    creatorId: 'test_creator_001',
    amount: 1000,
    currency: 'USD',
    productName: 'Test product',
    externalOrderId: \`test_order_\${Date.now()}\`,
    successUrl: process.env.SOLEDGIC_TEST_SUCCESS_URL || 'https://soledgic.com/sandbox/success',
  })

  console.log('3/4  Simulating payment via sandbox...')
  await soledgic.sandbox.completeCheckout({
    checkoutSessionId: checkout.checkoutSession.id,
    idempotencyKey: \`sandbox_complete_\${checkout.checkoutSession.id}\`,
  })

  console.log('4/4  Reading creator earnings balance...')
  const { wallets } = await soledgic.wallets.list({
    ownerId: 'test_creator_001',
    walletType: 'creator_earnings',
  })
  const balance = wallets[0]?.availableBalance ?? 0

  console.log('')
  console.log(\`  Done. Creator earnings: $\${(balance / 100).toFixed(2)}\`)
  console.log(\`  Checkout URL: \${checkout.checkoutSession.checkoutUrl}\`)
  console.log('')
  console.log('  Next: open sdk/typescript/README.md and adapt this to your real flow.')
}

main().catch((err) => {
  console.error('Test failed:', err.message)
  process.exit(1)
})
`

function writeTestFile(): boolean {
  const filePath = join(process.cwd(), TEST_FILE_NAME)
  if (existsSync(filePath)) return false
  writeFileSync(filePath, TEST_FILE_CONTENT)
  return true
}

function checkGitignore(): void {
  const gitignorePath = join(process.cwd(), '.gitignore')
  if (!existsSync(gitignorePath)) return
  const content = readFileSync(gitignorePath, 'utf8')
  const ignoresEnvFile = content
    .split(/\r?\n/)
    .map(line => line.trim())
    .filter(line => line && !line.startsWith('#'))
    .some(line => line === '.env' || line === '/.env' || line === '.env*' || line === '/.env*')

  if (!ignoresEnvFile) {
    console.log('\n  \x1b[33m!\x1b[0m  Add .env to .gitignore to avoid committing your API key')
  }
}

async function init(): Promise<void> {
  const port = pickPort()

  console.log('\n  \x1b[36msoledgic\x1b[0m init\n')
  console.log('  Opening your browser to authorize...')
  console.log(`  If it doesn\'t open, visit:\n`)
  console.log(`  \x1b[2m${AUTH_URL}/cli-auth?port=${port}\x1b[0m\n`)

  let done!: (result: { key: string; org: string }) => void
  let fail!: (err: Error) => void
  const result = new Promise<{ key: string; org: string }>((res, rej) => {
    done = res
    fail = rej
  })

  const server = createServer((req, res) => {
    const url = new URL(req.url!, `http://localhost:${port}`)
    if (url.pathname !== '/callback') { res.end(); return }

    const key = url.searchParams.get('key') ?? ''
    const org = url.searchParams.get('org') ?? ''

    res.writeHead(200, {
      'Content-Type': 'text/html; charset=utf-8',
      'Connection': 'close',
    })
    res.end(`<!doctype html><html><head><title>Soledgic CLI</title>
<style>body{font-family:system-ui,sans-serif;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;background:#f6f8f9}
.card{text-align:center;max-width:360px;padding:3rem 2rem;border-radius:8px;background:#fff;box-shadow:0 8px 40px rgba(0,0,0,.08)}
h2{margin:0 0 .75rem;font-size:1.4rem;color:#0d1117}p{margin:0;color:#6b7280;font-size:.95rem}</style></head>
<body><div class="card"><h2>Connected</h2><p>You can close this tab and return to your terminal.</p></div></body></html>`)

    server.close()
    done({ key, org })
  })

  server.listen(port, 'localhost', () => {
    openBrowser(`${AUTH_URL}/cli-auth?port=${port}`)
  })

  const timer = setTimeout(() => {
    server.close()
    fail(new Error('Timed out - no response after 5 minutes. Run soledgic init to try again.'))
  }, TIMEOUT_MS)

  const { key, org } = await result
  clearTimeout(timer)

  if (!key) {
    console.error('  Authorization failed - no key received.')
    process.exit(1)
  }

  writeEnv(key)
  const testFileWritten = writeTestFile()
  checkGitignore()

  console.log(`  \x1b[32m[ok]\x1b[0m  Connected${org ? ` to ${org}` : ''}`)
  console.log('  \x1b[32m[ok]\x1b[0m  Sandbox credentials saved to .env')
  if (testFileWritten) {
    console.log(`  \x1b[32m[ok]\x1b[0m  ${TEST_FILE_NAME} created\n`)
    console.log('  Run your first sandbox checkout:\n')
    console.log(`  \x1b[2m$\x1b[0m \x1b[36mnode ${TEST_FILE_NAME}\x1b[0m\n`)
  } else {
    console.log(`  \x1b[33m!\x1b[0m  ${TEST_FILE_NAME} already exists — left untouched\n`)
    console.log('  Get started:\n')
    console.log("  \x1b[2mimport Soledgic from '@soledgic/sdk'\x1b[0m")
    console.log('  \x1b[2mUse the saved environment value when constructing your client.\x1b[0m\n')
  }
}

function loadDotEnv(): Record<string, string> {
  const out: Record<string, string> = {}

  for (const fileName of ['.env.local', '.env']) {
    const envPath = join(process.cwd(), fileName)
    if (!existsSync(envPath)) continue

    for (const line of readFileSync(envPath, 'utf8').split(/\r?\n/)) {
      const trimmed = line.trim()
      if (!trimmed || trimmed.startsWith('#')) continue

      const normalized = trimmed.startsWith('export ') ? trimmed.slice(7).trim() : trimmed
      const eq = normalized.indexOf('=')
      if (eq <= 0) continue

      const key = normalized.slice(0, eq).trim()
      if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key) || out[key] !== undefined) continue

      let value = normalized.slice(eq + 1).trim()
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1)
      }
      out[key] = value
    }
  }

  return out
}

function normalizeApiBaseUrl(baseUrl: string): string {
  const normalized = baseUrl.trim().replace(/\/+$/, '')
  return normalized.endsWith('/v1') ? normalized.slice(0, -3) : normalized
}

function readCliVersion(): string {
  try {
    const packagePath = typeof __dirname !== 'undefined'
      ? join(__dirname, '..', 'package.json')
      : fileURLToPath(new URL('../package.json', import.meta.url))
    const packageJson = JSON.parse(readFileSync(packagePath, 'utf8')) as { version?: unknown }
    return typeof packageJson.version === 'string' ? packageJson.version : 'unknown'
  } catch {
    return 'unknown'
  }
}

async function doctor(): Promise<void> {
  const dotEnv = loadDotEnv()
  const env = (key: string) => process.env[key] ?? dotEnv[key] ?? ''

  const API_BASE = normalizeApiBaseUrl(env('SOLEDGIC_BASE_URL') || 'https://api.soledgic.com')
  const apiKey = env('SOLEDGIC_API_KEY') || env('SOLEDGIC_SECRET_KEY')

  console.log('\n  \x1b[36msoledgic\x1b[0m doctor\n')

  let allPassed = true

  function pass(label: string, detail = '') {
    console.log(`  \x1b[32m✓\x1b[0m  ${label}${detail ? `  \x1b[2m${detail}\x1b[0m` : ''}`)
  }
  function fail(label: string, hint = '') {
    allPassed = false
    console.log(`  \x1b[31m✗\x1b[0m  ${label}`)
    if (hint) console.log(`       \x1b[33mHint:\x1b[0m ${hint}`)
  }
  function warn(label: string, hint = '') {
    console.log(`  \x1b[33m!\x1b[0m  ${label}`)
    if (hint) console.log(`       \x1b[2m${hint}\x1b[0m`)
  }

  // 1. API key present
  if (!apiKey) {
    fail('Soledgic API key not set', "Set SOLEDGIC_API_KEY or SOLEDGIC_SECRET_KEY in your environment or .env file. You can also run 'soledgic init'.")
  } else {
    pass('API key found')
  }

  // 2. Key format
  if (apiKey) {
    if (apiKey.startsWith('slk_live_')) {
      pass('Key type: live', 'requests will charge real money')
    } else if (apiKey.startsWith('slk_test_')) {
      pass('Key type: test', 'safe to use in development')
    } else {
      fail('Unrecognized key format', "Expected prefix 'slk_test_' (test) or 'slk_live_' (live). Re-run 'soledgic init' to fetch a fresh key.")
    }
  }

  // 3. API reachability
  if (apiKey) {
    try {
      const res = await fetch(`${API_BASE}/v1/health-check`, {
        method: 'POST',
        headers: { 'x-api-key': apiKey, 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'status' }),
        signal: AbortSignal.timeout(8000),
      })
      if (res.ok) {
        pass('API reachable', `${API_BASE}/v1/health-check -> ${res.status}`)
      } else if (res.status === 401) {
        fail('API key rejected (401)', "The key was found but rejected. Check it was copied correctly. Run 'soledgic init' to re-authenticate.")
      } else {
        fail(`API returned ${res.status}`, "Unexpected response from the Soledgic API. Check your SOLEDGIC_BASE_URL or try again shortly.")
      }
    } catch {
      fail(`Cannot reach ${API_BASE}`, 'Check your network connection and SOLEDGIC_BASE_URL if you are using a custom endpoint.')
    }
  }

  // 4. Webhook secret
  const webhookSecret = env('SOLEDGIC_WEBHOOK_SECRET')
  if (!webhookSecret) {
    warn('SOLEDGIC_WEBHOOK_SECRET not set', 'Set this if you receive webhooks. Obtain it from your webhook endpoint config in the dashboard.')
  } else if (!webhookSecret.startsWith('wh_sec_slk')) {
    warn('SOLEDGIC_WEBHOOK_SECRET looks wrong', "Expected prefix 'wh_sec_slk'. Re-copy from the dashboard.")
  } else {
    pass('SOLEDGIC_WEBHOOK_SECRET found')
  }

  // 5. .gitignore check
  checkGitignore()

  // Summary
  console.log('')
  if (allPassed) {
    console.log('  \x1b[32mAll checks passed.\x1b[0m  Your Soledgic integration is configured correctly.\n')
  } else {
    console.log('  \x1b[31mSome checks failed.\x1b[0m  Fix the issues above before going live.\n')
    process.exit(1)
  }
}

const cmd = process.argv[2]

if (cmd === 'init') {
  init().catch((err: Error) => {
    console.error(`\n  \x1b[31m[error]\x1b[0m  ${err.message}\n`)
    process.exit(1)
  })
} else if (cmd === 'doctor') {
  doctor().catch((err: Error) => {
    console.error(`\n  \x1b[31m[error]\x1b[0m  ${err.message}\n`)
    process.exit(1)
  })
} else if (cmd === '--version' || cmd === '-v') {
  console.log(readCliVersion())
} else if (!cmd) {
  console.log('\n  Usage: soledgic <command>\n')
  console.log('  Commands:\n')
  console.log('    init      Connect your project to Soledgic')
  console.log('    doctor    Verify API key, connectivity, and webhook configuration\n')
} else {
  console.error(`\n  Unknown command: ${cmd}\n  Run soledgic for usage.\n`)
  process.exit(1)
}
